### ISSUE TITLE
Add example pages

### ISSUE THREAD

**Issue by taylorbryant** [taylorbryant/jekyll-starter-tailwind#68]
Make the starter a little less barebones and add a few example pages.

**Comment by jonathansimmons** [comment]
First thanks so much for this repo. A thought, what if you built out some of the sample page by just using using tailwindUI?

**Comment by taylorbryant** [comment]
@jonathansimmons Thank you for the kind words! Man, I would love to do that. Unfortunately, it’s prohibited by their license:

>Examples of usage not allowed by the license:
> - Creating a theme or template using the components and making it available either for sale or for free”

https://www.notion.so/Tailwind-UI-License-644418bb34ad4fa29aac9b82e956a867

However, I’m planning to put together some sensible example pages that I think will be a good starting point for people.

**Comment by pascalandy** [comment]
I think the only thing missing is a simple splash page over index.html + about-me.html + menu linking both. This way we could quickly understand how things are connected together.

**Comment by taylorbryant** [comment]
> I think the only thing missing is a simple splash page over index.html + about-me.html + menu linking both. This way we could quickly understand how things are connected together.
> 
> EDIT: Here is some inspiration:
> https://github.com/creativetimofficial/tailwind-starter-kit/tree/master/Landing%20Page/html-landing-page

Thanks for the recommendation! I'll take a look.
