### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by jacquescorbytuech** [taylorbryant/jekyll-starter-tailwind#72]
Hi Taylor,

Thanks for putting this starter theme together, it's been hugely useful so far!

My issue is similar to issue #64 .

I still get the same error as adrivn with the new update to the script you released, I was able to partially make this work after adding the following packages from npm:

win-node-env
win-spawn

Unfortunately I still get an error when trying to run "npm run build" locally on my machine or on Netlify, this is what Netlify returns when trying to deploy:

> 9:54:46 PM: Verify run directory
> 9:54:46 PM: Executing user command: npm run build
> 9:54:46 PM: npm
> 9:54:46 PM: ERR!
> 9:54:46 PM: missing script: build

I can confirm the script is running against the correct directory.

**Comment by taylorbryant** [comment]
@jacquescorbytuech Thank you for reaching out about this! I'll take a look over the weekend. Unfortunately, I don't have a Windows machine to test on, so I'm flying a bit blind here.

**Comment by jacquescorbytuech** [comment]
@taylorbryant No rush! Let me know if there's anything I can do to help test on my machine.

**Comment by taylorbryant** [comment]
Ohhhh I changed the command to `npm run build:production`. Can you try with that command and see if it works? I need to update the bit about deploying to Netlify in the README.

**Comment by taylorbryant** [comment]
I just added an alias `npm run build` command so it should work with either one now!

**Comment by jacquescorbytuech** [comment]
@taylorbryant Bingo! Thanks so much for looking into this!
